In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import svm
from sklearn.svm import SVC 
le = preprocessing.LabelEncoder() 
%matplotlib inline

In [2]:
data=pd.read_csv("/content/drive/MyDrive/Iris.csv")
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
col=data.columns
col

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [4]:
y=data["Species"].values
data=data.drop(["Id"],axis=1)
X=data.drop(["Species"],axis=1)
y=le.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
X

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [6]:
X["SepalLengthCm"]=X["SepalLengthCm"].astype("category")
X["PetalLengthCm"]=X["PetalLengthCm"].astype("category")
X["SepalWidthCm"]=X["SepalWidthCm"].astype("category")
X["PetalWidthCm"]=X["PetalWidthCm"].astype("category")
X["SepalLengthCm"]=X["SepalLengthCm"].cat.codes
X["PetalLengthCm"]=X["PetalLengthCm"].cat.codes
X["SepalWidthCm"]=X["SepalWidthCm"].cat.codes
X["PetalWidthCm"]=X["PetalWidthCm"].cat.codes
X

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0                8            14              4             1
1                6             9              4             1
2                4            11              3             1
3                3            10              5             1
4                7            15              4             1
..             ...           ...            ...           ...
145             24             9             28            19
146             20             4             26            15
147             22             9             28            16
148             19            13             30            19
149             16             9             27            14

[150 rows x 4 columns]

# **LINEAR SVM**

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=101)
lin=SVC(kernel='linear')
lin.fit(X_train, y_train)

SVC(kernel='linear')

In [8]:
y_pred=lin.predict(X_test)
y_pred

array([0, 0, 0, 1, 1, 2, 1, 1, 2, 0, 2, 0, 0, 2, 2, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 2, 0, 1])

In [9]:
accuracy = lin.score(X_test, y_test)
accuracy

0.9

# TRAIN SVM

In [45]:
data_train=pd.read_csv("/content/drive/MyDrive/train (1).csv")
X1=data_train.drop(["ID"],axis=1)
X1=data_train.drop(["US"],axis=1)
y1=data_train["US"].values
y1=le.fit_transform(y1)
data_train.head()

ID  Sales  CompetitorPrice  Income  Advertising  Population  Price  \
0   1   6.01              131      29           11         335    127   
1   2   6.50              148      51           16         148    150   
2   3   7.70              118      71           12          44     89   
3   4   7.78               86      54            0         497     64   
4   5  11.82              113      66           16         322     74   

  Location  Age  Education Urban   US  
0      Bad   33         12   Yes  Yes  
1   Medium   58         17    No  Yes  
2   Medium   67         18    No  Yes  
3      Bad   33         12   Yes   No  
4     Good   76         15   Yes  Yes

In [46]:
data_test=pd.read_csv("/content/drive/MyDrive/test (1).csv")
X2=data_test.drop(["ID"],axis=1)
X2=data_test.drop(["US"],axis=1)
y2=data_test["US"].values
y2=le.fit_transform(y2)
data_test.head()

ID  Sales  CompetitorPrice  Income  Advertising  Population  Price  \
0   1   6.39              131      21            8         220    171   
1   2   8.77              118      86            7         265    114   
2   3   6.89              129      69           10         289    110   
3   4   7.96              157      53            0         403    124   
4   5   7.57              112      88            2         243     99   

  Location  Age  Education Urban   US  
0     Good   29         14   Yes  Yes  
1     Good   52         15    No  Yes  
2   Medium   50         16    No  Yes  
3      Bad   58         16   Yes   No  
4   Medium   62         11   Yes  Yes

In [32]:
y1

array([1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,

In [33]:
y2

array([1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0])

In [49]:
X1

ID  Sales  CompetitorPrice  Income  Advertising  Population  Price  \
0      1   6.01              131      29           11         335    127   
1      2   6.50              148      51           16         148    150   
2      3   7.70              118      71           12          44     89   
3      4   7.78               86      54            0         497     64   
4      5  11.82              113      66           16         322     74   
..   ...    ...              ...     ...          ...         ...    ...   
344  345   9.70              138      61           12         156    120   
345  346   5.35              130      58           19         366    139   
346  347  11.70              144      69           11         131    104   
347  348   8.73              129      76           16          58    121   
348  349   5.71              121      42            4         188    118   

    Location  Age  Education Urban  
0        Bad   33         12   Yes  
1     Medium   58         17    No  
2     Medium   67         18    No  
3        Bad   33         12   Yes  
4       Good   76         15   Yes  
..       ...  ...        ...   ...  
344   Medium   25         14   Yes  
345      Bad   33         16   Yes  
346   Medium   47         11   Yes  
347   Medium   69         12   Yes  
348   Medium   54         15   Yes  

[349 rows x 11 columns]

In [50]:
X2

ID  Sales  CompetitorPrice  Income  Advertising  Population  Price  \
0    1   6.39              131      21            8         220    171   
1    2   8.77              118      86            7         265    114   
2    3   6.89              129      69           10         289    110   
3    4   7.96              157      53            0         403    124   
4    5   7.57              112      88            2         243     99   
5    6   8.89              122      76            0         270    100   
6    7   7.36              121      24            0         200    133   
7    8   8.75              143      77           25         448    156   
8    9   5.94              138      83            0         139    134   
9   10   7.52              116      72            0         237    128   
10  11   6.80              137     117            5         337    135   
11  12  10.14              145     119           16         294    113   
12  13  11.70              131      67            7         272    126   
13  14   6.41              142      30            0         472    136   
14  15   4.56              141      63            0         168    135   
15  16  13.39              149      69           20         366    134   
16  17   3.89              123     105            0         149    118   
17  18   8.54              139      35            0          95    129   
18  19  10.31              159      80            0         362    121   
19  20  10.06              113      35           10         269     80   
20  21  12.53              142      90            1         189    112   
21  22   2.93              143      21            5          81    160   
22  23  12.49              122      77           24         382    127   
23  24   8.65              123      76           18         218    120   
24  25  12.57              138     108           17         203    128   
25  26   4.42              121      90            0         150    108   
26  27   4.81              121      68            0         279    149   
27  28   4.69              132     113            0         131    124   
28  29   4.67              111      28            0         486    111   
29  30   5.17              138      35            6          60    143   
30  31  11.19               98     104            0         404     72   
31  32   8.97              132     107            0         144    125   
32  33   5.01              159      69            0         438    166   
33  34   8.01              128      39           12         356    118   
34  35   7.44              124      84            0         300    104   
35  36   5.86              136      70           12         171    152   
36  37   7.72              133      33           10         333    129   
37  38  12.98              113      33            0          14     63   
38  39   5.32              118      74            6         426    102   
39  40   4.68              124      46            0         199    135   
40  41   2.05              131      82            0         132    157   
41  42   8.78              130      30            0         391    100   
42  43   9.54              125      87            9         232    136   
43  44   8.19              111     105            0         466     97   
44  45   7.37              130      94            8         137    128   
45  46   2.52              124      61            0         333    138   
46  47   3.90              124      65           21         496    151   
47  48  11.48              121     120           13         140     87   
48  49   5.73              141      33            0         243    144   
49  50   8.57              116      78            1         158     99   
50  51   9.33              103      81            3         491     54   

   Location  Age  Education Urban  
0      Good   29         14   Yes  
1      Good   52         15    No  
2    Medium   50         16    No  
3       Bad

In [51]:
X1["Sales"]=X1["Sales"].astype("category")
X1["CompetitorPrice"]=X1["CompetitorPrice"].astype("category")
X1["Income"]=X1["Income"].astype("category")
X1["Advertising"]=X1["Advertising"].astype("category")
X1["Population"]=X1["Population"].astype("category")
X1["Price"]=X1["Price"].astype("category")
X1["Location"]=X1["Location"].astype("category")
X1["Age"]=X1["Age"].astype("category")
X1["Education"]=X1["Education"].astype("category")
X1["Urban"]=X1["Urban"].astype("category")

X1["Sales"]=X1["Sales"].cat.codes
X1["CompetitorPrice"]=X1["CompetitorPrice"].cat.codes
X1["Income"]=X1["Income"].cat.codes
X1["Advertising"]=X1["Advertising"].cat.codes
X1["Population"]=X1["Population"].cat.codes
X1["Price"]=X1["Price"].cat.codes
X1["Location"]=X1["Location"].cat.codes
X1["Age"]=X1["Age"].cat.codes
X1["Education"]=X1["Education"].cat.codes
X1["Urban"]=X1["Urban"].cat.codes


X2["Sales"]=X2["Sales"].astype("category")
X2["CompetitorPrice"]=X2["CompetitorPrice"].astype("category")
X2["Income"]=X2["Income"].astype("category")
X2["Advertising"]=X2["Advertising"].astype("category")
X2["Population"]=X2["Population"].astype("category")
X2["Price"]=X2["Price"].astype("category")
X2["Location"]=X2["Location"].astype("category")
X2["Age"]=X2["Age"].astype("category")
X2["Education"]=X2["Education"].astype("category")
X2["Urban"]=X2["Urban"].astype("category")

X2["Sales"]=X2["Sales"].cat.codes
X2["CompetitorPrice"]=X2["CompetitorPrice"].cat.codes
X2["Income"]=X2["Income"].cat.codes
X2["Advertising"]=X2["Advertising"].cat.codes
X2["Population"]=X2["Population"].cat.codes
X2["Price"]=X2["Price"].cat.codes
X2["Location"]=X2["Location"].cat.codes
X2["Age"]=X2["Age"].cat.codes
X2["Education"]=X2["Education"].cat.codes
X2["Urban"]=X2["Urban"].cat.codes

X1['Location']=le.fit_transform(X1['Location'])
X1['Urban']=le.fit_transform(X1['Urban'])

X2['Location']=le.fit_transform(X2['Location'])
X2['Urban']=le.fit_transform(X2['Urban'])

In [52]:
X1

ID  Sales  CompetitorPrice  Income  Advertising  Population  Price  \
0      1    100               42       8           11         156     59   
1      2    115               59      29           16          71     80   
2      3    160               29      49           12          20     21   
3      4    164                2      32            0         238      4   
4      5    274               24      44           16         148      9   
..   ...    ...              ...     ...          ...         ...    ...   
344  345    233               49      39           12          75     52   
345  346     75               41      36           19         171     71   
346  347    273               55      47           11          64     36   
347  348    198               40      54           16          28     53   
348  349     89               32      21            4          86     50   

     Location  Age  Education  Urban  
0           0    8          2      1  
1           2   33          7      0  
2           2   42          8      0  
3           0    8          2      1  
4           1   51          5      1  
..        ...  ...        ...    ...  
344         2    0          4      1  
345         0    8          6      1  
346         2   22          1      1  
347         2   44          2      1  
348         2   29          5      1  

[349 rows x 11 columns]

In [53]:
X2

ID  Sales  CompetitorPrice  Income  Advertising  Population  Price  \
0    1     17               15       0            7          20     39   
1    2     34                6      26            6          24     15   
2    3     20               13      14            9          29     11   
3    4     27               27       8            0          39     19   
4    5     25                3      28            2          23      6   
5    6     36                8      18            0          26      7   
6    7     21                7       1            0          17     25   
7    8     33               24      19           18          43     35   
8    9     16               20      24            0           7     26   
9   10     24                5      16            0          22     23   
10  11     19               19      36            4          33     27   
11  12     41               25      37           12          30     14   
12  13     45               15      12            6          27     21   
13  14     18               23       3            0          45     28   
14  15      6               22      10            0          13     27   
15  16     50               26      14           15          36     26   
16  17      3                9      32            0          10     16   
17  18     30               21       5            0           3     24   
18  19     42               28      21            0          35     18   
19  20     40                4       5            9          25      3   
20  21     47               23      29            1          15     13   
21  22      2               24       0            4           2     37   
22  23     46                8      19           17          37     22   
23  24     32                9      18           14          19     17   
24  25     48               20      34           13          18     23   
25  26      5                7      29            0          11     10   
26  27     10                7      13            0          28     32   
27  28      9               16      35            0           4     19   
28  29      7                2       2            0          46     12   
29  30     12               20       5            5           1     30   
30  31     43                0      31            0          40      2   
31  32     37               16      33            0           9     20   
32  33     11               28      14            0          42     38   
33  34     28               12       6           10          34     16   
34  35     23               10      25            0          31      9   
35  36     15               18      15           10          14     34   
36  37     26               17       4            9          32     24   
37  38     49                4       4            0           0      1   
38  39     13                6      17            5          41      8   
39  40      8               10       7            0          16     27   
40  41      0               15      23            0           5     36   
41  42     35               14       3            0          38      7   
42  43     39               11      27            8          21     28   
43  44     29                2      32            0          44      5   
44  45     22               14      30            7           6     23   
45  46      1               10       9            0          32     29   
46  47      4               10      11           16          48     33   
47  48     44                7      38           11           8      4   
48  49     14               22       4            0          23     31   
49  50     31                5      20            1          12      6   
50  51     38                1      22            3          47      0   

    Location  Age  Education  Urban  
0          1    4          4      1  
1          1   16          5      0  
2          2   15          6      0  
3  

In [54]:
lin=SVC(kernel='linear')
lin.fit(X1, y1)

SVC(kernel='linear')

In [57]:
y_pred=lin.predict(X2)
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1])

In [58]:
accuracy = lin.score(X2, y2)
accuracy

0.8431372549019608